name: CI Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

env:
  REGISTRY: daryladriene
  BACKEND_IMAGE_NAME: lush-dew
  FRONTEND_IMAGE_NAME: lush-dew

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push backend Docker image
        working-directory: ./backend/cosmeticshop
        run: |
          docker build \
            -t $REGISTRY/$BACKEND_IMAGE_NAME:backend_${{ github.run_number }} \
            -f Dockerfile .
          docker push $REGISTRY/$BACKEND_IMAGE_NAME:backend_${{ github.run_number }}

      - name: Build & push frontend Docker image
        working-directory: ./frontend
        run: |
          docker build \
            -t $REGISTRY/$FRONTEND_IMAGE_NAME:frontend_${{ github.run_number }} \
            -f Dockerfile .
          docker push $REGISTRY/$FRONTEND_IMAGE_NAME:frontend_${{ github.run_number }}

      - name: Update both image tags
        run: |
          sed -i 's|\(tag1: "\)v[0-9]*"|\1${{ github.run_number }}"|' helm/lushdew-chart/values.yaml
          sed -i 's|\(tag2: "\)v[0-9]*"|\1${{ github.run_number }}"|' helm/lushdew-chart/values.yaml

      - name: Commit & push updated Helm chart
        run: |
          git config --global user.name "daryladrien"
          git config --global user.email "daryladrien27@gmail.com"
          git add helm/lushdew-chart/values.yaml
          git commit -m "ci: bump image tag to ${{ github.run_number }}"
          git push
